/**
 * MiniEnv CLI - Terraform Integration Commands
 *
 * Generate Terraform .tfvars and JSON files
 */

import type { CLIArgs, MiniEnvConfig, Environment } from '../../../types.js'
import { MiniEnvClient } from '../../../client.js'
import { loadEncryptionKey } from '../../../lib/config-loader.js'

interface TerraformContext {
  args: CLIArgs
  config: MiniEnvConfig | null
  project: string
  service?: string
  environment: Environment
  verbose: boolean
  jsonOutput: boolean
}

/**
 * Generate Terraform .tfvars file
 */
export async function runTfVars(context: TerraformContext): Promise<void> {
  const { args, config, project, service, environment, verbose, jsonOutput } = context

  if (!project) {
    console.error('Error: Project not specified')
    process.exit(1)
  }

  if (verbose) {
    console.error(`Generating Terraform tfvars for ${project}/${environment}`)
  }

  // Build connection string
  const connectionString = args.backend || args.b || config?.backend?.url
  const passphrase = config ? await loadEncryptionKey(config) : undefined

  const client = new MiniEnvClient({
    connectionString: connectionString || undefined,
    passphrase: passphrase || undefined
  })

  try {
    await client.connect()

    const vars = await client.export(project, environment, service)

    if (Object.keys(vars).length === 0) {
      console.error('Warning: No variables found')
      return
    }

    if (jsonOutput) {
      console.log(JSON.stringify({
        format: 'tfvars',
        project,
        environment,
        variableCount: Object.keys(vars).length
      }))
    } else {
      // Generate .tfvars content
      const tfvars = generateTfVars(vars, {
        project,
        service,
        environment
      })
      console.log(tfvars)
    }
  } finally {
    await client.disconnect()
  }
}

/**
 * Generate Terraform JSON variables file
 */
export async function runTfJson(context: TerraformContext): Promise<void> {
  const { args, config, project, service, environment, verbose, jsonOutput } = context

  if (!project) {
    console.error('Error: Project not specified')
    process.exit(1)
  }

  if (verbose) {
    console.error(`Generating Terraform JSON for ${project}/${environment}`)
  }

  // Build connection string
  const connectionString = args.backend || args.b || config?.backend?.url
  const passphrase = config ? await loadEncryptionKey(config) : undefined

  const client = new MiniEnvClient({
    connectionString: connectionString || undefined,
    passphrase: passphrase || undefined
  })

  try {
    await client.connect()

    const vars = await client.export(project, environment, service)

    if (Object.keys(vars).length === 0) {
      console.error('Warning: No variables found')
      return
    }

    // Generate JSON output
    // Terraform expects variable names in lowercase with underscores
    const tfVars: Record<string, string> = {}
    for (const [key, value] of Object.entries(vars)) {
      // Convert to terraform-friendly name
      const tfKey = key.toLowerCase()
      tfVars[tfKey] = value
    }

    // Also include an env_vars map for convenience
    const output = {
      // Individual variables
      ...tfVars,
      // Full map for use with for_each
      env_vars: vars
    }

    console.log(JSON.stringify(output, null, 2))
  } finally {
    await client.disconnect()
  }
}

/**
 * Generate .tfvars content
 */
function generateTfVars(
  vars: Record<string, string>,
  metadata: { project: string; service?: string; environment: string }
): string {
  const lines: string[] = [
    '# Generated by minienv',
    `# Project: ${metadata.project}`,
    `# Environment: ${metadata.environment}`,
    metadata.service ? `# Service: ${metadata.service}` : null,
    '# DO NOT EDIT - changes will be overwritten',
    ''
  ].filter(Boolean) as string[]

  // Add individual variables (lowercase names for Terraform convention)
  for (const [key, value] of Object.entries(vars)) {
    const tfKey = key.toLowerCase()
    lines.push(`${tfKey} = ${formatTfValue(value)}`)
  }

  // Add a map variable containing all env vars
  lines.push('')
  lines.push('# All environment variables as a map')
  lines.push('env_vars = {')

  for (const [key, value] of Object.entries(vars)) {
    lines.push(`  "${key}" = ${formatTfValue(value)}`)
  }

  lines.push('}')

  return lines.join('\n')
}

/**
 * Format value for Terraform HCL
 */
function formatTfValue(value: string): string {
  // Always use double quotes for strings in Terraform
  // Escape special characters
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')

  return `"${escaped}"`
}
