/**
 * Vaulter MCP Tools - Kubernetes Handlers
 *
 * Handlers for k8s_secret, k8s_configmap operations
 */

import fs from 'node:fs'
import { VaulterClient } from '../../../client.js'
import {
  findConfigDir,
  isSplitMode,
  getSecretsFilePath,
  getConfigsFilePath
} from '../../../lib/config-loader.js'
import { parseEnvFile } from '../../../lib/env-parser.js'
import type { VaulterConfig, Environment, EnvVar } from '../../../types.js'
import type { ToolResponse } from '../config.js'
import { sanitizeK8sName, base64Encode } from '../config.js'

export async function handleK8sSecretCall(
  client: VaulterClient,
  config: VaulterConfig | null,
  project: string,
  environment: Environment,
  service: string | undefined,
  args: Record<string, unknown>
): Promise<ToolResponse> {
  const namespace = (args.namespace as string) || `${project}-${environment}`
  const name = (args.name as string) || (service ? `${service}-secrets` : `${project}-secrets`)

  let secretVars: Record<string, string> = {}

  // Check for split mode - read from local file
  if (config && isSplitMode(config)) {
    const configDir = findConfigDir()
    if (configDir) {
      const secretsPath = getSecretsFilePath(config, configDir, environment)
      if (fs.existsSync(secretsPath)) {
        secretVars = parseEnvFile(secretsPath)
      } else {
        return { content: [{ type: 'text', text: `Error: Secrets file not found: ${secretsPath}` }] }
      }
    } else {
      return { content: [{ type: 'text', text: 'Error: No .vaulter directory found' }] }
    }
  } else {
    // Fetch from backend and filter by sensitive=true
    const allVars = await client.list({ project, environment, service })
    const secrets = allVars.filter(v => v.sensitive === true)

    for (const v of secrets) {
      secretVars[v.key] = v.value
    }
  }

  if (Object.keys(secretVars).length === 0) {
    return { content: [{ type: 'text', text: 'Warning: No secret variables found (none marked as sensitive)' }] }
  }

  // Generate YAML
  const lines = [
    '# Generated by vaulter MCP',
    '# kubectl apply -f - <<< "$(vaulter_k8s_secret)"',
    'apiVersion: v1',
    'kind: Secret',
    'metadata:',
    `  name: ${sanitizeK8sName(name)}`,
    `  namespace: ${sanitizeK8sName(namespace)}`,
    '  labels:',
    `    app.kubernetes.io/managed-by: vaulter`,
    `    app.kubernetes.io/environment: ${environment}`,
    'type: Opaque',
    'data:'
  ]

  for (const [key, value] of Object.entries(secretVars)) {
    lines.push(`  ${key}: ${base64Encode(value)}`)
  }

  return { content: [{ type: 'text', text: lines.join('\n') }] }
}

export async function handleK8sConfigMapCall(
  client: VaulterClient,
  config: VaulterConfig | null,
  project: string,
  environment: Environment,
  service: string | undefined,
  args: Record<string, unknown>
): Promise<ToolResponse> {
  const namespace = (args.namespace as string) || `${project}-${environment}`
  const name = (args.name as string) || (service ? `${service}-config` : `${project}-config`)

  let configVars: Record<string, string> = {}

  // Check for split mode - read from local file
  if (config && isSplitMode(config)) {
    const configDir = findConfigDir()
    if (configDir) {
      const configsPath = getConfigsFilePath(config, configDir, environment)
      if (fs.existsSync(configsPath)) {
        configVars = parseEnvFile(configsPath)
      } else {
        return { content: [{ type: 'text', text: `Error: Configs file not found: ${configsPath}` }] }
      }
    } else {
      return { content: [{ type: 'text', text: 'Error: No .vaulter directory found' }] }
    }
  } else {
    // Fetch from backend and filter by sensitive=false (configs only)
    const allVars = await client.list({ project, environment, service })
    const configs = allVars.filter(v => v.sensitive !== true)

    for (const v of configs) {
      configVars[v.key] = v.value
    }
  }

  if (Object.keys(configVars).length === 0) {
    return { content: [{ type: 'text', text: 'Warning: No config variables found (all are marked as sensitive)' }] }
  }

  // Generate YAML
  const lines = [
    '# Generated by vaulter MCP',
    '# kubectl apply -f - <<< "$(vaulter_k8s_configmap)"',
    'apiVersion: v1',
    'kind: ConfigMap',
    'metadata:',
    `  name: ${sanitizeK8sName(name)}`,
    `  namespace: ${sanitizeK8sName(namespace)}`,
    '  labels:',
    `    app.kubernetes.io/managed-by: vaulter`,
    `    app.kubernetes.io/environment: ${environment}`,
    'data:'
  ]

  for (const [key, value] of Object.entries(configVars)) {
    const needsQuote = value.includes(':') || value.includes('#') || value.includes('\n')
    if (needsQuote) {
      lines.push(`  ${key}: "${value.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`)
    } else {
      lines.push(`  ${key}: ${value}`)
    }
  }

  return { content: [{ type: 'text', text: lines.join('\n') }] }
}
